### ISSUE TITLE
sbt assembly failing

### ISSUE THREAD

**Issue by awolfe76** [cfpb/grasshopper#143]
I pulled down master and when running `sbt assembly` I get 3 failed tests.

_1 here_

``` shell
[info] CensusJsonProtocolSpec:
[info] Status
[info] - should convert to and from JSON
[info] ParsedAddressInput
[info] - should convert to and from JSON *** FAILED ***
[info]   java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
[info]   at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:105)
[info]   at spray.json.BasicFormats$IntJsonFormat$.write(BasicFormats.scala:25)
[info]   at spray.json.ProductFormats$class.productElement2Field(ProductFormats.scala:45)
[info]   at grasshopper.census.protocol.CensusJsonProtocolSpec.productElement2Field(CensusJsonProtocolSpec.scala:10)
[info]   at spray.json.ProductFormatsInstances$$anon$4.write(ProductFormatsInstances.scala:96)
[info]   at spray.json.ProductFormatsInstances$$anon$4.write(ProductFormatsInstances.scala:92)
[info]   at spray.json.PimpedAny.toJson(package.scala:39)
[info]   at grasshopper.census.protocol.CensusJsonProtocolSpec$$anonfun$2.apply$mcV$sp(CensusJsonProtocolSpec.scala:20)
[info]   at grasshopper.census.protocol.CensusJsonProtocolSpec$$anonfun$2.apply(CensusJsonProtocolSpec.scala:18)
[info]   at grasshopper.census.protocol.CensusJsonProtocolSpec$$anonfun$2.apply(CensusJsonProtocolSpec.scala:18)
[info]   ...
```

_2 here_

``` shell
[info] CensusGeocodeServiceSpec:
[info] Tiger Address Line Service
[info] - should respond to status
[info] - should geocode an interpolated address point *** FAILED ***
[info]   java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
[info]   at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:105)
[info]   at spray.json.BasicFormats$IntJsonFormat$.write(BasicFormats.scala:25)
[info]   at spray.json.ProductFormats$class.productElement2Field(ProductFormats.scala:45)
[info]   at grasshopper.census.api.CensusGeocodeServiceSpec.productElement2Field(CensusGeocodeServiceSpec.scala:18)
[info]   at spray.json.ProductFormatsInstances$$anon$4.write(ProductFormatsInstances.scala:96)
[info]   at spray.json.ProductFormatsInstances$$anon$4.write(ProductFormatsInstances.scala:92)
[info]   at spray.json.PimpedAny.toJson(package.scala:39)
[info]   at grasshopper.census.api.CensusGeocodeServiceSpec$$anonfun$2.apply$mcV$sp(CensusGeocodeServiceSpec.scala:58)
[info]   at grasshopper.census.api.CensusGeocodeServiceSpec$$anonfun$2.apply(CensusGeocodeServiceSpec.scala:51)
[info]   at grasshopper.census.api.CensusGeocodeServiceSpec$$anonfun$2.apply(CensusGeocodeServiceSpec.scala:51)
[info]   ...
[info] - should return BadRequest when invalid JSON is POSTed
[info] - should return empty features array when searching for address that doesn't exist *** FAILED ***
[info]   java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Integer
[info]   at scala.runtime.BoxesRunTime.unboxToInt(BoxesRunTime.java:105)
[info]   at spray.json.BasicFormats$IntJsonFormat$.write(BasicFormats.scala:25)
[info]   at spray.json.ProductFormats$class.productElement2Field(ProductFormats.scala:45)
[info]   at grasshopper.census.api.CensusGeocodeServiceSpec.productElement2Field(CensusGeocodeServiceSpec.scala:18)
[info]   at spray.json.ProductFormatsInstances$$anon$4.write(ProductFormatsInstances.scala:96)
[info]   at spray.json.ProductFormatsInstances$$anon$4.write(ProductFormatsInstances.scala:92)
[info]   at spray.json.PimpedAny.toJson(package.scala:39)
[info]   at grasshopper.census.api.CensusGeocodeServiceSpec$$anonfun$4.apply$mcV$sp(CensusGeocodeServiceSpec.scala:84)
[info]   at grasshopper.census.api.CensusGeocodeServiceSpec$$anonfun$4.apply(CensusGeocodeServiceSpec.scala:77)
[info]   at grasshopper.census.api.CensusGeocodeServiceSpec$$anonfun$4.apply(CensusGeocodeServiceSpec.scala:77)
[info]   ...
```

And then see this:

``` shell
[info] ScalaTest
[info] Run completed in 7 seconds, 778 milliseconds.
[info] Total number of tests run: 18
[info] Suites: completed 5, aborted 0
[info] Tests: succeeded 15, failed 3, canceled 0, ignored 0, pending 0
[info] *** 3 TESTS FAILED ***
[error] Failed: Total 18, Failed 3, Errors 0, Passed 15
[error] Failed tests:
[error]     grasshopper.census.protocol.CensusJsonProtocolSpec
[error]     grasshopper.census.api.CensusGeocodeServiceSpec
```

And:

``` shell
[error] (census/test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 15 s, completed Sep 1, 2015 10:31:11 AM
```

**Comment by jmarin** [comment]
@awolfe76 Try doing `sbt clean assembly` and see if that works for you. I think this happens because the signature for the JSON converted hasn't changed, but the types are different. I had to add the clean step in Jenkins to fix this.

**Comment by awolfe76** [comment]
@jmarin that did it. Thanks!

Should we update step 3 in the [Docker part of the README](https://github.com/cfpb/grasshopper#docker) to show that?
